.PHONY: test api worker-jobs worker-ai worker-whatsapp

test:
	go test ./...

api:
	go run ./cmd/api

worker-jobs:
	go run ./cmd/worker_jobs

worker-ai:
	go run ./cmd/worker_ai

worker-whatsapp:
	go run ./cmd/worker_whatsapp
